### ISSUE TITLE
The call to the method interval here is likely a mistake.  

### ISSUE THREAD

**Issue by griffithac** [itsdan/acts_as_learnable#1]
https://github.com/dankimio/acts_as_learnable/blob/2bffb223691da31ae8d6519e0cc24dd21f402fee/lib/acts_as_learnable/base.rb#L74

I corrected the code on my side to read:

```ruby
    (repetitions - 1) * easiness_factor
```

It seems to be working correctly for me now.

Thanks for your work.

**Comment by dankimio** [comment]
Hi @griffithac, thanks for the report!

Can you  have a look at [repetition](https://github.com/dankimio/repetition) gem? It shouldn't have this issue.

**Comment by dankimio** [comment]
Thank you! Resolved in https://github.com/dankimio/acts_as_learnable/commit/3ddb8618a23c02c52bc672bfc51887c0800686f6.
